name: Publish Docker

env:
  VERSION: 1.0.0.${{ github.run_number }}

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Adliance.Kimai.Vacations/**'
      - '.github/workflows/docker-build-push.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Adliance.Kimai.Vacations/Dockerfile
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            ghcr.io/adliance/kimai-vacations:latest
            ghcr.io/adliance/kimai-vacations:${{ env.VERSION }}
